Cluboard/Inventory_Management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('base.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Cluboard/base/urls.py
from django.contrib import admin
from django.urls import path
from base import views


urlpatterns = [
    path("", views.index, name="index"),

    path("club_view/<int:club_id>", views.club_view, name="club_view"), 
    path("club_add/", views.club_add, name="club_add"), 
    path("club_statistics/<int:club_id>", views.club_statistics, name="club_statistics"),

    path("user_add/<int:club_id>", views.user_add, name="user_add"), 
    path("existing_user_add/<int:club_id>", views.existing_user_add, name="existing_user_add"), 
    path("user_delete/<int:user_id>", views.user_delete, name="user_delete"), 

    path("item_add/<int:club_id>", views.item_add, name="item_add"), 
    path("item_update/<int:club_id>/<int:item_id>", views.item_update, name="item_update"), 
    path("item_delete/<int:item_id>", views.item_delete, name="item_delete"), 
    path("items_view/<int:club_id>", views.items_view, name="items_view"), 

    path("request_add/<int:club_id>", views.request_add, name="request_add"),   
    path("request_approve/<int:request_id>", views.request_approve, name="request_approve"), 
    path("request_reject/<int:request_id>", views.request_reject, name="request_reject"), 

    path("error_page/", views.error_page, name="error_page"),    
]

Cluboard/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from base.models import Club

# Create your models here.
class Info(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    roll_no = models.CharField(max_length=100)
    
class Permission(models.Model):
    actions = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.actions[:20]

class Role(models.Model):

    MEMBER = 'member'
    CONVENOR = 'convenor'
    ADMIN = 'admin'

    ROLE_CHOICES = [
        (MEMBER, 'Member'),
        (CONVENOR, 'Convenor'),
        (ADMIN, 'Admin')
    ]

    name = models.CharField(max_length=50, choices=ROLE_CHOICES, default=MEMBER)
    permissions = models.ManyToManyField(Permission, blank=True, null=True)

    def __str__(self):
        return self.name

class Permission_Assignment(models.Model):
    club = models.ForeignKey(Club,blank=True, null = True, on_delete=models.CASCADE)
    user = models.ForeignKey(User, blank=False, null = False, on_delete=models.CASCADE)
    role = models.ForeignKey(Role, blank=False, null = False, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.club_id) + " " + str(self.user_id) + " " + str(self.role.name)

Cluboard/base/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Club(models.Model):
    #Many Clubs have many Users
    users = models.ManyToManyField(User, blank=True, null=True)
    club_name =  models.CharField(max_length = 100)
    description = models.TextField(blank=True, null=True)
    logo = models.ImageField(upload_to="images/", default = "")

    def __str__(self):
        return self.club_name

class Item(models.Model):
    item_name = models.CharField(max_length=100)
    qty = models.IntegerField()
    club = models.ForeignKey(Club, blank=True, null = True, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="images/", default = "")  

    def __str__(self):
        return self.item_name + ' ' + self.club.club_name
        
class Request(models.Model):
    STATUS = (('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'))
    requested_by = models.ForeignKey(User, null=True, on_delete = models.SET_NULL)
    club = models.ForeignKey(Club, blank=True, null = True, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, null=True, on_delete=models.SET_NULL)
    qty = models.IntegerField()
    status = models.CharField(max_length=100, null=True, choices=STATUS, default='Pending')
    date_created = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return self.requested_by.username + ' ' + self.item.item_name 

Cluboard/base/forms.py
from django import forms
from django.forms import ModelForm

from base.models import Club, Item, Request

class ClubForm(forms.ModelForm):
    
    class Meta:
        model = Club
        fields = '__all__'

class ItemForm(forms.ModelForm):
    
    class Meta:
        model = Item
        fields = '__all__'

class RequestForm(forms.ModelForm):
    
    class Meta:
        model = Request
        fields = ['requested_by', 'club', 'item', 'qty']
        

Cluboard/base/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.urls import reverse
from base.models import Club, Request, Item
from accounts.models import Permission_Assignment, Role
from django.contrib.auth.models import User
from django.db.models import Count

from django.contrib import messages
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required, user_passes_test
from django.conf import settings

from base.forms import *
from accounts.forms import *

from math import ceil

# Functions to check user type and authorisation thereby

# Function to check if user can access a view method
def can_user_access(user_id, action, club_id=None):
    user_permissions = ''
    if club_id:
        try:
            user_permissions = Permission_Assignment.objects.get(
                club=club_id, user=user_id).role.permissions.all()
        except:
            Permission_Assignment.DoesNotExist
    else:
        try:
            user_permissions = Permission_Assignment.objects.get(
                user=user_id).role.permissions.all()
        except:
            Permission_Assignment.DoesNotExist
    
    # Find permission in the permissions string of the
    # associated role
    if user_permissions:
        permissions_string = ""
        for permission in user_permissions:
            permissions_string += permission.actions + ","

        permissions_array = permissions_string.split(",")[:-1]
        if action in permissions_array:
            return True
    return False

# Function to check if a request is AJAX
def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'


@login_required(login_url='login')
# login_url is the page to be redirected to in case the function evaluates to false
def index(request):
    clubs = request.user.club_set.all()

    if request.user.is_superuser:
        clubs = Club.objects.all()

    context = {'clubs': clubs}
    return render(request, 'index.html', context)


@login_required(login_url='login')
def user_add(request, club_id):
    if can_user_access(request.user.id, 'user_add', club_id):
        club = Club.objects.get(id=club_id)
        user_form = CreateUserForm()
        info_form = InfoForm()

        initial = {'club': club}
        permission_assignment_form = PermissionAssignmentForm(initial=initial)

        # Only current club should be displayed
        permission_assignment_form.fields['club'].queryset = Club.objects.filter(
            id=club_id)

        # Only non existing members should be displayed
        existing_club_users = club.users.all()
        permission_assignment_form.fields['user'].queryset = User.objects.exclude(
            id__in=[o.id for o in existing_club_users])

        context = {
            'user_form': user_form,
            'info_form': info_form,
            'club': club,
            'permission_assignment_form': permission_assignment_form
        }

        if request.method == 'POST':
            user_form = CreateUserForm(request.POST)
            info_form = InfoForm(request.POST)
            permission_assignment_form = PermissionAssignmentForm(request.POST)
            if user_form.is_valid():
                user_form.save()

                # Getting required data to display message
                first_name = user_form.cleaned_data.get('first_name')
                last_name = user_form.cleaned_data.get('last_name')
                username = user_form.cleaned_data.get('username')

                # Getting required data from info_form
                roll_no = request.POST['roll_no']
                user = User.objects.get(username=username)

                # Creating an Info object linked to this user
                user_info = Info(user=user, roll_no=roll_no)
                user_info.save()

                # Adding user to club
                club.users.add(user)

                # Assigning role to the user
                role_id = request.POST['role']
                role = Role.objects.get(id=role_id)
                permission_assignment = Permission_Assignment(
                    club=club, user=user, role=role)
                permission_assignment.save()

                messages.success(
                    request, f'Account was successfully created for {first_name} {last_name} and added to {club.club_name}!')
                return redirect(reverse('club_view', args=[club_id]))
            else:
                messages.info(request, 'Error creating user')

        return render(request, 'user_add.html', context)
    else:
        return render(request, 'error_page.html')


@login_required(login_url='login')
def existing_user_add(request, club_id):
    if can_user_access(request.user.id, 'user_add', club_id):
        club = Club.objects.get(id=club_id)
        form = PermissionAssignmentForm(request.POST)

        data = {}

        if is_ajax(request=request):
            if form.is_valid():
                form.save()
                user_id = request.POST['user']

                user = User.objects.get(id=user_id)
                club.users.add(user)
                name = user.first_name + " " + user.last_name
                data['name'] = name
                data['club'] = club.club_name
                data['status'] = 'ok'
                return JsonResponse(data)
            else:
                messages.info(request, 'Error adding user!')

        return render(request, 'error_page.html')


@login_required(login_url='login')
def user_delete(request, user_id):
    if can_user_access(request.user.id, 'user_delete'):
        user = User.objects.get(id=user_id)
        club = user.club_set.first()
        user.delete()
        messages.info(request, 'User deleted successfully!')
        return redirect(reverse('club_view', args=[club.id]))


@login_required(login_url='login')
def club_add(request):
    # Adding a new club
    form = ClubForm()
    if request.method == 'POST':
        form = ClubForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Club added successfully!')
            return redirect('/')
    context = {'form': form}
    return render(request, 'club_add.html', context)


@login_required(login_url='login')
def club_view(request, club_id):
    if can_user_access(request.user.id, "club_view", club_id):
        club = Club.objects.get(id=club_id)
        members = club.users.all()
        context = {'club': club, 'members': members}

        return render(request, 'club_view.html', context)
    else:
        return redirect('error_page')


@login_required(login_url='login')
def item_add(request, club_id):
    if can_user_access(request.user.id, 'item_add', club_id):
        club = Club.objects.get(id=club_id)
        initial = {'club': club}

        # Adding a new item
        form = ItemForm(initial=initial)
        form.fields['club'].queryset = Club.objects.filter(id=club_id)
        if request.method == 'POST':
            form = ItemForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                messages.success(request, 'Item added successfully!')
                return redirect(reverse('items_view', args=[club_id]))
        context = {'club': club, 'form': form}
        return render(request, 'item_add.html', context)
    else:
        return redirect('error_page')


def view_all_requests(club):
    return club.request_set.all().order_by('-date_created')


@login_required(login_url='login')
def items_view(request, club_id):
    if can_user_access(request.user.id, 'items_view', club_id):
        # Display all items belonging to that club as a carousel of cards
        club = Club.objects.get(id=club_id)
        items = club.item_set.all()
        all_items = []
        n = len(items)
        nSlides = n//4 + ceil(n/4-n//4)  # logic for displaying slides
        all_items.append([items, range(1, nSlides), nSlides])

        # Display all requests pertaining to that club
        reqs = view_all_requests(club)

        if can_user_access(request.user.id, 'view_all_requests', club_id) == False:
            reqs = reqs.filter(requested_by=request.user.id)

        context = {'club': club, 'all_items': all_items, 'reqs': reqs}
        return render(request, 'items_view.html', context)
    else:
        return redirect('error_page')


@login_required(login_url='login')

def item_update(request, club_id, item_id):
    # Update an existing item
    if can_user_access(request.user.id, 'item_update', club_id):
        item = Item.objects.get(id=item_id)
        club = Club.objects.get(id=club_id)
        form = ItemForm(instance=item)
        form.fields['club'].queryset = Club.objects.filter(id=item.club.id)
        if request.method == 'POST':
            form = ItemForm(request.POST, request.FILES, instance=item)
            if form.is_valid():
                item.save()
                messages.success(request, 'Item updated successfully!')
                return redirect(reverse('items_view', args=[item.club.id]))

        context = {'club': club, 'form': form, 'item': item}
        return render(request, 'item_update.html', context)
    else:
        return redirect('error_page')


@login_required(login_url='login')
def item_delete(request, item_id):
    item = Item.objects.get(id=item_id)
    club_id = item.club.id
    if can_user_access(request.user.id, 'item_delete', club_id):
        item.delete()
        messages.info(request, 'Item deleted successfully!')
        return redirect(reverse('items_view', args=[club_id]))
    else:
        return redirect('error_page')


@login_required(login_url='login')
def request_approve(request, request_id):
    # Approve the request if there is sufficient quantity available
    req = Request.objects.get(id=request_id)
    club_id = req.item.club.id
    if can_user_access(request.user.id, 'request_approve', club_id):

Cluboard/base/templates/base.html
<!-- This template acts as a base for index.html and club_add.html -->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&display=swap" rel="stylesheet">

    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <!--DataTable  -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.0/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.12.0/js/jquery.dataTables.js"></script>

    <!-- Chart.js -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.8.0/dist/chart.min.js"></script>

    <title>{% block title %}{% endblock title %} | InvManage</title>
    <style>
        .cards {
            display: flex;
            /* flex-direction: row; */
            margin: 1rem;
            flex-wrap: wrap;
            align-items: center;
            /* justify-content: center; */
            /* max-width: 100%; */
        }

        .card {
            background-color: #25274D;
            color: white;
        }

        body {
            background-color: black;
            font-family: 'Nunito', sans-serif;
            color: white;
        }

        h3,
        h4,
        a,
        p {
            color: white;
            text-decoration: none;
        }

        a:hover {
            color: rgb(180, 175, 175);
        }

        #id_users {
            background-color: rgb(29, 27, 27);
            color: white;
        }
        th,
        td {
            color: white;
        }

        .table_head {
            background-color: #25274D !important;
        }

        .table-striped>tbody>tr:nth-child(odd)>td,
        .table-striped>tbody>tr:nth-child(odd)>th {
            background-color: rgb(37, 36, 36);
        }

        input[type=text],
        input[type=number],
        input[type=email],
        input[type=password],
        textarea,select {
            margin-right: 3px;
            border: 1px solid rgb(51, 47, 47);
            border-radius: 5px;
            padding: 8px;
            background-color: rgb(29, 27, 27);
            color: white;
        }

        button {
            border: 1px solid rgb(51, 47, 47);
            background-color: #25274D;
            color: white;
            padding: 10px;
            font-size: 15px;
            border-radius: 5px;
            cursor: pointer;
            text-decoration: none;
        }
        .button {
            border: 1px solid rgb(51, 47, 47);
            background-color: rgb(240, 52, 52);
            color: white;
            padding: 10px;
            font-size: 15px;
            border-radius: 5px;
            cursor: pointer;
            text-decoration: none;
        }
        
        label{
            width: 10%;
        }
        .password_wrapper, .helptext{
            color:rgb(240, 155, 155);
            font-size: 80%;
        }
        .neumorphism-card {
            border-radius: 20px;
            background: linear-gradient(145deg, #101010, #131313);
            box-shadow:  12px 12px 24px #0f0f0f,
                        -12px -12px 24px #151515;
            padding: 20px;
        }

        .centered-div {
            width: 50%;
            margin: auto;
        }

        .centered-text {
            margin: auto;
            width: 50%;
            margin-bottom: 20px;
            text-align: center;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">InvManage</a>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'profile' request.user.id %}">Profile</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show my-0" role="alert">
        <strong>{{ message }}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}

    {% block body %}{% endblock body %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>
</body>

</html>

Cluboard/base/templates/club_add.html
{% extends 'base.html' %}

{% block title %}Add Club{% endblock title %}

{% block body %}

<div class="my-4 card neumorphism-card centered-div">

    <div class="my-2 centered-text">
        <h3>Add Club</h3>
        <hr>
    </div>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <p><label class="form_label">Users: </label>{{form.users}}</p>
        <p><label class="form_label" onclick="toggleConvenor()">Club: </label> {{form.club_name}}</p>
        <!-- <p id="convenor-input" style="display: none;"><label class="form_label">Convenor: </label> {{form.club_name}}</p> -->
        <p><label class="form_label">Description: </label> {{form.description}}</p>
        <p><label class="form_label">Logo: </label> {{form.logo}}</p>
        <button type="submit">Add Club</button>
    </form>
</div>
<script>
    // function toggleConvenor() {
    //     var x = document.getElementById("convenor-input");
    //     if (x.style.display === "none") {
    //         x.style.display = "block";
    //     } else {
    //         x.style.display = "none";
    //     }
    // }
</script>
{% endblock body %}

Cluboard/base/templates/club_bar_chart.html
<div class="card neumorphism-card">
    <canvas id="barChart" width="20px" height="20px"></canvas>
</div>

<script>
$(document).ready(function() {
    const ctx = document.getElementById('barChart').getContext('2d');
    const barChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: [{% for item in items_list %} '{{item}}',{% endfor %}],
            datasets: [{
                label: '# of Requests',
                data: [{% for req in requests_count_by_item %} '{{req}}',{% endfor %}],
                backgroundColor: [
                    'rgba(255, 99, 132,0.5)',
                    'rgba(54, 162, 235, 0.5)',
                    'rgba(255, 206, 86, 0.5)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)'
                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            },
            plugins: {
                title: {
                    display: true,
                    text: 'Requests Distribution by item'
                }
            }
        }
    });
})

</script>

Cluboard/base/templates/error_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error</title>
</head>
<body>
    <p>You are not authorised to view this page.</p>
</body>
</html>

Cluboard/base/templates/index.html
{% extends 'base.html' %}
{% load can_user_access_tag %}
{% block title %}Home{% endblock title %}

{% block body %}

<div class="container neumorphism-card my-5" >
    <div class="centered-text">
        <h3 class="centered-div">Clubs
            {% can_user_access user.id 'club_add' 1 as can_club_add %}

            {% if can_club_add %} 
                <a id="add-link" href="{% url 'club_add' %}"><i class="fa fa-plus-circle"></i></a>
            {% endif %}
        </h3>
        <hr>
    </div>
    <div class="cards mx-0">
        {% for club in clubs %}
        <div class="card mx-3 my-2" style="width: 12rem; height: 17rem;">
            <img class="card-img-top" src="/media/{{club.logo}}" height="180px" width="180px">
            <div class="card-body">
                <p class="card-title"><a href="{% url 'items_view' club.id %}">{{club.club_name}}</p></a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock body %}

Cluboard/base/templates/user_add.html
{% extends 'main.html' %}

{% block title %}Add User{% endblock title%}

{% block body%}

<div class="my-4 card neumorphism-card centered-div"> 
    <div>
        <h3 class="centered-text">Add User</h3>
        <ul class="nav justify-content-center nav-pills">
            <li class="nav-item">
                <button class="nav-link active" onclick="toggleNewUser()" id="btnNewUser">New User</a>
            </li>
            <li class="nav-item">
                <button class="nav-link" href="#" onclick="toggleExistingUser()" id="btnExistingUser">Existing User</a>
            </li>
        </ul>
        <hr>
    </div>
    <div id="alertBox"></div>
    <div id="newUserFormDiv">
        <form action="" method="POST"  id="newUserForm">
            {% csrf_token %}
            {{user_form.as_p}}
            <p><label class ="form_label">Roll No:</label> {{info_form.roll_no}}</p>
            <p>
                <label for="role">Role:</label>
                <select name="role" id="role" required>
                <option value="" selected="">---------</option>
                <option value="1">member</option>
                <option value="2">convenor</option>
                <option value="3">admin</option>
                </select>
              </p>
            <button type="submit">Add User</button>
        </form>
    </div>
    <div style="display:none" id="existingUserFormDiv">
        <form action="" method="POST" id="existingUserForm">
            {% csrf_token %}
            {{permission_assignment_form.as_p}}
            <button type="submit" id="submitExistingUserBtn">Add User</button>
            <button type="button" id="spinnerBtn" style="display:none;" disabled>
                <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                Loading...
            </button>
        </form>
    </div>
    <!-- <form action="" method="POST">
        {% csrf_token %}
        <p><label for="id_first_name">First name:</label> <input type="text" name="first_name" maxlength="150"
                id="id_first_name"></p>
        <p><label for="id_last_name">Last name:</label> <input type="text" name="last_name" maxlength="150"
                id="id_last_name"></p>
        <p><label for="id_username">Username:</label> <input type="text" name="username" maxlength="150" autofocus=""
                required="" id="id_username"> <span class="helptext">Required. 150 characters or fewer. Letters, digits
                and @/./+/-/_ only.</span></p>
        <p><label for="id_email">Email address:</label> <input type="email" name="email" maxlength="254" id="id_email">
        </p>
        <p><label for="id_password1">Password:</label> <input type="password" name="password1"
                autocomplete="new-password" required="" id="id_password1"> <span class="helptext"></span></p>
        <ul class="password_wrapper">
            <li>Your password can’t be too similar to your other personal information.</li>
            <li>Your password must contain at least 8 characters.</li>
            <li>Your password can’t be a commonly used password.</li>
            <li>Your password can’t be entirely numeric.</li>
        </ul>
        <p></p>
        <p><label for="id_password2">Password confirmation:</label> <input type="password" name="password2"
                autocomplete="new-password" required="" id="id_password2"> <span class="helptext">Enter the same
                password as before, for verification.</span></p>
        <p><label for="id_roll_no">Roll no:</label> <input type="text" name="roll_no" maxlength="100" required=""
                id="id_roll_no"></p>
        <p><label for="id_designation">Designation:</label> <select name="designation" id="id_designation">
                <option value="Member" selected="">Member</option>

                <option value="Convenor">Convenor</option>

                <option value="Admin">Admin</option>

            </select></p>
        <button type="submit">Add User</button>
    </form> -->
</div>

<script>
    var btnNewUser = document.getElementById("btnNewUser");
    var btnExistingUser = document.getElementById("btnExistingUser");
    var newUserFormDiv = document.getElementById("newUserFormDiv");
    var existingUserFormDiv = document.getElementById("existingUserFormDiv");
    var addUserBtn = document.getElementById("submitExistingUserBtn");
    var spinnerBtn = document.getElementById("spinnerBtn");

    // Function to toggle New User Form
    function toggleNewUser() {
        btnNewUser.classList.add("active");
        btnExistingUser.classList.remove("active");
        newUserFormDiv.style.display = "block";
        existingUserFormDiv.style.display = "none";
    }

    // Function to toggle Existing User Form
    function toggleExistingUser() {
        btnExistingUser.classList.add("active");
        btnNewUser.classList.remove("active");
        newUserFormDiv.style.display = "none";
        existingUserFormDiv.style.display = "block";
    }

    // To submit existing user form
    const alertBox = document.getElementById("alertBox");
    const existingUserForm = document.getElementById("existingUserForm");
    const club_id = "{{club.id}}";
    const url = '/existing_user_add/' + club_id

    // Function to show alerts
    const handleAlerts = (type, text) => {
        alertBox.innerHTML = `<div class="alert alert-${type} alert-dismissible fade show my-0" role="alert">
                                <strong>${text}<strong>
                            </div>`
    }

    // Get respective values 
    const club = document.getElementById("id_club");
    const user = document.getElementById("id_user");
    const role = document.getElementById("id_role");

    // csrf token
    const csrf = document.querySelector("input[name=csrfmiddlewaretoken]").value;

    // Submit form via AJAX
    existingUserForm.addEventListener("submit", e=>{
        e.preventDefault();
        spinnerBtn.style.display = 'block';
        addUserBtn.style.display = 'none';

        const formData = new FormData();
        formData.append('csrfmiddlewaretoken',csrf);
        formData.append('club', club.value)
        formData.append('user', user.value)
        formData.append('role', role.value)

        $.ajax({
            type: 'POST',
            url: url,
            data: formData,
            success: function(response){
                const sText = `Successfully added ${response.name} to ${response.club}`
                handleAlerts('success', sText)
                setTimeout(()=>{
                    alertBox.innerHtml = ``
                }, 2000)
                existingUserForm.reset();
                spinnerBtn.style.display = 'none';
                addUserBtn.style.display = 'block';
            },
            error: function(error){
                handleAlerts('danger', 'Oops, something went wrong!')
                setTimeout(()=>{
                    alertBox.innerHtml = ""
                }, 2000)
                spinnerBtn.style.display = 'none';
                addUserBtn.style.display = 'block';
            },
            cache: false,
            contentType: false,
            processData: false,
        })
    })
</script>
{% endblock body%}